spring.application.name=api-clientes

# Porta do servidor web
server.port=8081

# Endereco do banco de dados
datasource.host=jdbc:postgresql://localhost:5432/bd-api-clientes

# Usuario do banco de dados
datasource.user=postgres

# Senha do banco de dados
datasource.pass=coti

# Permissoes de CORS
cors.enabled=http://localhost:4200


